config:
  exporters:
    logging:
      loglevel: debug
    otlp:
      endpoint: tempo:4317
      tls:
        insecure: true
  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [logging]
      traces:
        receivers: [otlp]
        exporters: [logging, otlp]