config: |-
  server:
    http_listen_port: 3100

  search_enabled: true

  distributor:
    search_tags_deny_list:
      - "instance"
      - "version"
    receivers:
      jaeger:
        protocols:
          thrift_http:
          grpc:
          thrift_binary:
          thrift_compact:
      zipkin:
      otlp:
        protocols:
          http:
          grpc:
      opencensus:

  ingester:
    trace_idle_period: 10s
    max_block_bytes: 1_000_000
    max_block_duration: 5m

  compactor:
    compaction:
      compaction_window: 1h
      max_block_bytes: 100_000_000
      block_retention: 1h
      compacted_block_retention: 10m

  storage:
    trace:
      backend: local
      block:
        bloom_filter_false_positive: .05
        index_downsample_bytes: 1000
        encoding: zstd
      wal:
        path: /tmp/tempo/wal
        encoding: snappy
      local:
        path: /tmp/tempo/blocks
      pool:
        max_workers: 100
        queue_depth: 10000
  overrides:
    per_tenant_override_config: /conf/overrides.yaml

tempo:
  overrides:
    "single-tenant":
      search_tags_allow_list:
        - "instance"
      ingestion_rate_strategy: "local"
      ingestion_rate_limit_bytes: 15000000
      ingestion_burst_size_bytes: 20000000
      max_traces_per_user: 10000
      max_global_traces_per_user: 0
      max_bytes_per_trace: 50000
      max_search_bytes_per_trace: 0
      max_bytes_per_tag_values_query: 5000000
      block_retention: 0s
